package com.jing.monitor.service;

import com.jing.monitor.core.CourseCrawler;
import com.jing.monitor.model.SectionInfo;
import com.jing.monitor.model.StatusMapping;
import com.jing.monitor.repository.FileRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.LocalTime;

/**
 * Service class responsible for scheduling and executing the course monitoring task.
 * Annotated with @Service to let Spring manage it as a Bean.
 */
@Service
@RequiredArgsConstructor // Automatically generates a constructor for all final fields (Lombok)
public class SchedulerService {

    // Dependencies are injected automatically by Spring via the constructor generated by Lombok.
    private final CourseCrawler crawler;
    private final FileRepository repository;
    private final MailService mailService;

    // Inject target section ID from application.properties
    @Value("${uw-api.target-section}")
    private String targetSection;

    // State flag to prevent spamming emails for the same continuous status
    private boolean alertSent = false;

    // public SchedulerService(CourseCrawler crawler, FileRepository repository) {
    // this.crawler = crawler;
    // this.repository = repository;
    // this.mailService = mailService;
    // }

    /**
     * Periodic task to check course status.
     * The execution interval is defined in 'monitor.poll-interval-ms'.
     */
    @Scheduled(fixedRateString = "${monitor.poll-interval-ms}")
    public void monitorTask() {
        // Debug: System.out.println("[Scheduler] Heartbeat...");

        try {
            // 1. Fetch course status via Crawler
            SectionInfo info = crawler.fetchCourseStatus(targetSection);

            if (info != null) {
                // 2. Log to console
                System.out.println("[Time: " + LocalTime.now() + "] " + info);

                // 3. Persist to file repository
                repository.save(info);

                // 4. Alert Logic
                if (info.getStatus() == StatusMapping.OPEN) {
                    // Only send alert if we haven't sent one for this opening window yet
                    if (!alertSent) {
                        System.out.println("\n\n🔥🚨🔥 ALERT: SECTION " + targetSection + " IS OPEN! 🔥🚨🔥\n");
                        mailService.sendCourseOpenAlert(targetSection, info.toString());
                        alertSent = true; // Set flag to true to suppress further emails
                    }
                }
                else if (info.getStatus() == StatusMapping.WAITLISTED) {
                    if (!alertSent) {
                        System.out.println("\n\n🔥🚨🔥 ALERT: WAITLIST OPEN FOR " + targetSection + "! 🔥🚨🔥\n");
                        mailService.sendCourseWaitlistedAlert(targetSection, info.toString()); // Assuming you added this method
                        alertSent = true;
                    }
                }
                else {
                    // RESET Logic: If course becomes CLOSED, reset the flag.
                    // This allows us to receive a new alert if it re-opens later.
                    if (alertSent) {
                        System.out.println("[Info] Course closed (or status changed). Resetting alert flag.");
                        alertSent = false;
                    }
                }
            } else {
                System.out.println("[Warning] Fetch returned null. Target section not found.");
            }

        } catch (Exception e) {
            System.err.println("Error in scheduled task: " + e.getMessage());
            e.printStackTrace();
        }
    }
}