# application.properties
uw-api.term-id=1264
uw-api.subject-id=266
uw-api.course-id=004289
uw-api.target-section=60035
uw-api.user-agent=...

monitor.poll-interval-ms=60000

# ===============================
# Email Configuration (SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=keqinglee000@gmail.com
spring.mail.password=akhv iqrt newu pomg

# default SMTP protocol config
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# customized recipient config
app.mail.from=keqinglee000@gmail.com
app.mail.to=ygong68@wisc.edu