# UW-Madison API Configuration
# Term: 1264 = Spring 2026
app.term-id=1264
# Subject: 266 = Computer Sciences
app.subject-id=266
# Course: 004289 = CS 577 (Intro to Algorithms)
app.course-id=004289

# Monitoring Settings
app.target-section=60035
app.poll-interval-seconds=60

# User Agent (Disguise as the browser)
app.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36